#!/bin/sh

rm -rf debtmp
mkdir debtmp

[ -f version ] || python ./mscript.py configure

Version=`cat version`

python ./mscript.py dist
ln "roxterm-$Version.tar.gz" "debtmp/roxterm_$Version.orig.tar.gz"

cd debtmp
tar xf "roxterm_$Version.orig.tar.gz"
cd "roxterm-$Version"

if [ "$EMAIL" != "h@realh.co.uk" ] ; then
    SIGNOPTS="-uc -us"
else
    SIGNOPTS=""
fi

echo "Building in directory " `pwd`
debuild -i -I $SIGNOPTS $@
