#!/bin/sh

rm -rf debtmp
mkdir debtmp

python ./mscript.py configure

Version=`cat version`

python ./mscript.py dist
ln "build/roxterm-$Version.tar.bz2" "debtmp/roxterm_$Version.orig.tar.bz2"

cd debtmp
tar xf "roxterm_$Version.orig.tar.bz2"
cd "roxterm-$Version"

if [ "$EMAIL" != "h@realh.co.uk" ] ; then
    SIGNOPTS="-uc -us"
else
    SIGNOPTS=""
fi

echo "Building in directory " `pwd`
debuild -i -I $SIGNOPTS $@
