#!/bin/sh
MAIN=master
RELEASE="$1"
if [ -z "$RELEASE" ] ; then
	echo "You forgot the version number" >&2
	exit 1
fi
if echo "$RELEASE" grep -q 'beta' ; then
    TAG="Beta"
else
    TAG="Release"
    printf $RELEASE > version
    printf $RELEASE > release_version
    git commit release_version -m "Version $RELEASE"
fi
git tag -s --force $RELEASE -m "$TAG $RELEASE" $2
if [ $TAG = "Release"] ; then
    git checkout stable
    git merge $MAIN
    git push origin stable:stable
fi
git checkout $MAIN
