#!/bin/sh
MAIN=master
RELEASE="$1"
if [ -z "$RELEASE" ] ; then
	echo "You forgot the version number" >&2
	exit 1
fi
printf $RELEASE > version
printf $RELEASE > release_version
git commit release_version -m "Version $RELEASE"
git tag -s --force $RELEASE -m "Release $RELEASE" $2
git checkout stable
git merge $MAIN
git push origin stable:stable
git checkout $MAIN
