#ifndef MENU_LABELS_H
#define MENU_LABELS_H

#include "defns.h"

// This is the single source of truth for the menu labels for consistent
// translations etc. They are also used with underscores stripped to build
// accelerator paths.

typedef enum {
    MENUTREE_NULL_ID = -1,

    MENUTREE_SSH_HOST,
    MENUTREE_OPEN_IN_BROWSER,
    MENUTREE_OPEN_IN_MAILER,
    MENUTREE_OPEN_IN_FILER,
    MENUTREE_VOIP_CALL,
    MENUTREE_COPY_URI,
    MENUTREE_URI_SEPARATOR,

    MENUTREE_FILE,
    MENUTREE_EDIT,
    MENUTREE_VIEW,
    MENUTREE_SEARCH,
    MENUTREE_PREFERENCES,
    MENUTREE_TABS,
    MENUTREE_HELP,

    MENUTREE_FILE_NEW_WINDOW,
    MENUTREE_FILE_NEW_TAB,
    MENUTREE_FILE_NEW_WINDOW_WITH_PROFILE,
    MENUTREE_FILE_NEW_WINDOW_WITH_PROFILE_HEADER,
    MENUTREE_FILE_NEW_TAB_WITH_PROFILE,
    MENUTREE_FILE_NEW_TAB_WITH_PROFILE_HEADER,
    MENUTREE_FILE_CLOSE_TAB,
    MENUTREE_FILE_CLOSE_WINDOW,
    MENUTREE_FILE_SAVE_BUFFER_AS,
    MENUTREE_FILE_SAVE_BUFFER,
    MENUTREE_FILE_SAVE_SESSION,

    MENUTREE_EDIT_SELECT_ALL,
    MENUTREE_EDIT_COPY,
    MENUTREE_EDIT_PASTE,
    MENUTREE_EDIT_COPY_AND_PASTE,
    MENUTREE_EDIT_SET_WINDOW_TITLE,
    MENUTREE_EDIT_RESET,
    MENUTREE_EDIT_RESET_AND_CLEAR,
    MENUTREE_EDIT_RESPAWN,

    MENUTREE_VIEW_SHOW_MENUBAR,
    MENUTREE_VIEW_SHOW_TAB_BAR,
    MENUTREE_VIEW_FULLSCREEN,
    MENUTREE_VIEW_BORDERLESS,
    MENUTREE_VIEW_ZOOM_IN,
    MENUTREE_VIEW_ZOOM_OUT,
    MENUTREE_VIEW_ZOOM_NORM,
    MENUTREE_VIEW_SCROLL_UP,
    MENUTREE_VIEW_SCROLL_DOWN,
    MENUTREE_VIEW_SCROLL_PAGE_UP,
    MENUTREE_VIEW_SCROLL_PAGE_DOWN,
    MENUTREE_VIEW_SCROLL_HALF_PAGE_UP,
    MENUTREE_VIEW_SCROLL_HALF_PAGE_DOWN,
    MENUTREE_VIEW_SCROLL_TO_TOP,
    MENUTREE_VIEW_SCROLL_TO_BOTTOM,

    MENUTREE_SEARCH_FIND,
    MENUTREE_SEARCH_FIND_NEXT,
    MENUTREE_SEARCH_FIND_PREVIOUS,

    MENUTREE_PREFERENCES_SELECT_PROFILE,
    MENUTREE_PREFERENCES_SELECT_COLOUR_SCHEME,
    MENUTREE_PREFERENCES_SELECT_SHORTCUTS,
    MENUTREE_PREFERENCES_EDIT_CURRENT_PROFILE,
    MENUTREE_PREFERENCES_EDIT_CURRENT_COLOUR_SCHEME,
    MENUTREE_PREFERENCES_EDIT_CURRENT_SHORTCUTS_SCHEME,
    MENUTREE_PREFERENCES_CONFIG_MANAGER,

    MENUTREE_TABS_DETACH_TAB,
    MENUTREE_TABS_CLOSE_TAB,
    MENUTREE_TABS_CLOSE_OTHER_TABS,
    MENUTREE_TABS_NAME_TAB,
    MENUTREE_TABS_PREVIOUS_TAB,
    MENUTREE_TABS_NEXT_TAB,
    MENUTREE_TABS_MOVE_TAB_LEFT,
    MENUTREE_TABS_MOVE_TAB_RIGHT,

    MENUTREE_HELP_SHOW_MANUAL,
    MENUTREE_HELP_ABOUT,


    MENUTREE_NUM_IDS,

    MENUTREE_TABS_FIRST_FIXED = MENUTREE_TABS_DETACH_TAB,
    MENUTREE_TABS_LAST_FIXED = MENUTREE_TABS_MOVE_TAB_RIGHT + 1,
                                /* +1 for separator */
    MENUTREE_TABS_FIRST_DYNAMIC =
    MENUTREE_TABS_LAST_FIXED - MENUTREE_TABS_FIRST_FIXED + 3
    /* +3 because there are 3 separators in total */
} MenuTreeID;


#define TOP_LEVEL_MENU_ITEMS \
    N_("_File"), MENUTREE_FILE, \
    N_("_Edit"), MENUTREE_EDIT, \
    N_("_View"), MENUTREE_VIEW, \
    N_("_Search"), MENUTREE_SEARCH, \
    N_("_Preferences"), MENUTREE_PREFERENCES, \
    N_("Ta_bs"), MENUTREE_TABS, \
    N_("_Help"), MENUTREE_HELP


// The only reason you might want to translate this is for the translation
// hints that appear in generated Shortcuts config files.
#define MENUTREE_URI_LABEL N_("URI")


#define FILE_MENU_ITEMS \
    N_("_New Window"), MENUTREE_FILE_NEW_WINDOW, \
    N_("New _Tab"), MENUTREE_FILE_NEW_TAB, \
    N_("New _Window With Profile"), MENUTREE_FILE_NEW_WINDOW_WITH_PROFILE, \
    N_("New Tab With _Profile"), MENUTREE_FILE_NEW_TAB_WITH_PROFILE, \
    N_("C_lose Tab"), MENUTREE_FILE_CLOSE_TAB, \
    N_("_Close Window"), MENUTREE_FILE_CLOSE_WINDOW, \
    "_", MENUTREE_NULL_ID, \
    N_("Save Buffer _As"), MENUTREE_FILE_SAVE_BUFFER_AS, \
    N_("Save _Buffer"), MENUTREE_FILE_SAVE_BUFFER, \
    "_", MENUTREE_NULL_ID, \
    N_("_Save Session"), MENUTREE_FILE_SAVE_SESSION


#define COPY_PASTE_MENU_ITEMS \
    N_("Select _All"), MENUTREE_EDIT_SELECT_ALL, \
    N_("_Copy"), MENUTREE_EDIT_COPY, \
    N_("_Paste"), MENUTREE_EDIT_PASTE, \
    N_("Cop_y & Paste"), MENUTREE_EDIT_COPY_AND_PASTE, \
    "_", MENUTREE_NULL_ID

#define RESET_MENU_ITEMS \
    N_("_Reset"), MENUTREE_EDIT_RESET, \
    N_("Reset And C_lear"), MENUTREE_EDIT_RESET_AND_CLEAR

#define EDIT_MENU_ITEMS \
    COPY_PASTE_MENU_ITEMS, \
    N_("_Set Window Title"), MENUTREE_EDIT_SET_WINDOW_TITLE, \
    RESET_MENU_ITEMS, \
    "_", MENUTREE_NULL_ID, \
    N_("Res_tart command"), MENUTREE_EDIT_RESPAWN


#define SHOW_MENU_BAR_ITEM \
    N_("Show Menu_bar"), MENUTREE_VIEW_SHOW_MENUBAR

#define VIEW_MENU_ITEMS \
    SHOW_MENU_BAR_ITEM, \
    N_("_Always Show Tab Bar"), MENUTREE_VIEW_SHOW_TAB_BAR, \
    N_("_Full Screen"), MENUTREE_VIEW_FULLSCREEN, \
    N_("_Border_less"), MENUTREE_VIEW_BORDERLESS, \
    "_", MENUTREE_NULL_ID, \
    N_("Zoom _In"), MENUTREE_VIEW_ZOOM_IN, \
    N_("Zoom _Out"), MENUTREE_VIEW_ZOOM_OUT, \
    N_("_Normal Size"), MENUTREE_VIEW_ZOOM_NORM, \
    "_", MENUTREE_NULL_ID, \
    N_("Scroll _Up One Line"), MENUTREE_VIEW_SCROLL_UP, \
    N_("Scroll _Down One Line"), MENUTREE_VIEW_SCROLL_DOWN, \
    N_("Scroll Up One _Page"), MENUTREE_VIEW_SCROLL_PAGE_UP, \
    N_("Scroll Do_wn One Page"), MENUTREE_VIEW_SCROLL_PAGE_DOWN, \
    N_("Scroll Up One _Half Page"), MENUTREE_VIEW_SCROLL_HALF_PAGE_UP, \
    N_("Scroll Down One Hal_f Page"), MENUTREE_VIEW_SCROLL_HALF_PAGE_DOWN, \
    N_("Scroll To _Top"), MENUTREE_VIEW_SCROLL_TO_TOP, \
    N_("Scroll To _Bottom"), MENUTREE_VIEW_SCROLL_TO_BOTTOM


#define SEARCH_MENU_ITEMS \
    N_("_Find"), MENUTREE_SEARCH_FIND, \
    N_("Find _Next"), MENUTREE_SEARCH_FIND_NEXT, \
    N_("Find _Previous"), MENUTREE_SEARCH_FIND_PREVIOUS


#define PREFERENCES_MENU_ITEMS \
    N_("Select _Profile"), MENUTREE_PREFERENCES_SELECT_PROFILE, \
    N_("Select _Colour Scheme"), MENUTREE_PREFERENCES_SELECT_COLOUR_SCHEME, \
    N_("Select _Shortcuts Scheme"), MENUTREE_PREFERENCES_SELECT_SHORTCUTS, \
    "_", MENUTREE_NULL_ID, \
    N_("_Edit Current Profile"), MENUTREE_PREFERENCES_EDIT_CURRENT_PROFILE, \
    N_("E_dit Current Colour Scheme"), \
    MENUTREE_PREFERENCES_EDIT_CURRENT_COLOUR_SCHEME, \
    N_("Edi_t Current Shortcuts Scheme"), \
    MENUTREE_PREFERENCES_EDIT_CURRENT_SHORTCUTS_SCHEME, \
    "_", MENUTREE_NULL_ID, \
    N_("Configuration _Manager"), MENUTREE_PREFERENCES_CONFIG_MANAGER


#define TABS_MENU_ITEMS \
    N_("_Detach Tab"), MENUTREE_TABS_DETACH_TAB, \
    N_("_Close Tab"), MENUTREE_TABS_CLOSE_TAB, \
    N_("Close _Other Tabs"), MENUTREE_TABS_CLOSE_OTHER_TABS, \
    N_("Na_me Tab"), MENUTREE_TABS_NAME_TAB, \
    "_", MENUTREE_NULL_ID, \
    N_("_Previous Tab"), MENUTREE_TABS_PREVIOUS_TAB, \
    N_("_Next Tab"), MENUTREE_TABS_NEXT_TAB, \
    "_", MENUTREE_NULL_ID, \
    N_("Move Tab _Left"), MENUTREE_TABS_MOVE_TAB_LEFT, \
    N_("Move Tab _Right"), MENUTREE_TABS_MOVE_TAB_RIGHT, \
    "_", MENUTREE_NULL_ID


#define HELP_MENU_ITEMS \
        N_("Show _Manual"), MENUTREE_HELP_SHOW_MANUAL, \
        N_("_About ROXTerm"), MENUTREE_HELP_ABOUT


#define URI_MENU_ITEMS \
    N_("_SSH to host"), MENUTREE_SSH_HOST, \
    N_("_Open link"), MENUTREE_OPEN_IN_BROWSER, \
    N_("Send e_mail"), MENUTREE_OPEN_IN_MAILER, \
    N_("_Open file/directory in filer"), MENUTREE_OPEN_IN_FILER, \
    N_("_Call"), MENUTREE_VOIP_CALL, \
    N_("_Copy address to clipboard"), MENUTREE_COPY_URI, \
    N_("_"), MENUTREE_URI_SEPARATOR


#endif // MENU_LABELS_H
